FROM mcr.microsoft.com/devcontainers/base:jammy

# Download and nstall Quarto
RUN wget "https://github.com/quarto-dev/quarto-cli/releases/download/v1.2.313/quarto-1.2.313-linux-amd64.deb"
RUN sudo dpkg -i ./quarto-1.2.313-linux-amd64.deb 